[workspace]
channels = ["knime", "conda-forge"]
conda-pypi-map = {}
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
python = "3.*"
knime-extension = "*"
knime-python-base = "5.*"
knime-python-versions = "5.*"
intervaltree = "*"
pydotplus = "*"
graphviz = "*"
python-graphviz = "*"
pip = "*"

[feature.build.dependencies]
python = "*"
knime-extension-bundling = "5.*"
nodejs = "*"

[feature.debug.dependencies]
debugpy = "*"

[feature.build.tasks]
build = { args = [{ "arg" = "dest", "default" = "./local-update-site" }, { "arg" = "update_sites_version", "default" = "latest" }], cmd = "build-python-extension . {{ dest }} --update-sites-version {{ update_sites_version }}"}


[environments]
build = {features = ["build"], no-default-feature = true}
debug = {features = ["debug"]}

[pypi-dependencies]
powl = "*"
promoai = "*"
pm4py = "*"

[pypi-options]
no-build = true
